### ISSUE TITLE
Install foreman_cockpit 2.0.1 on clean install of Katello 3.0.0 (CentOS 7) results in "Connection reset by peer" when clicking on host

### ISSUE THREAD

**Issue by worsco** [theforeman/foreman_cockpit#8]
- I've installed Katello 3.0.0 on clean CentOS 7.  All packages are from official RPMs.
- The only host I've registered into Foreman/Katello is the master host (same host running Foreman/Katello).
- Cockpit is NOT installed on this machine.
- I then installed the cockpit plugin for Foreman:
  yum install tfm-rubygem-foreman_cockpit
- Restarted foreman.
- Clicking on this Host in 'All hosts' results in "Connection reset by peer"
  [2016-08-01_foreman_cockpit_error.txt](https://github.com/theforeman/foreman_cockpit/files/394494/2016-08-01_foreman_cockpit_error.txt)
- Uninstalling the plugin allows you to click on the host:
  yum remove tfm-rubygem-foreman_cockpit

**Comment by worsco** [comment]
Is this commit supposed to fix the problem?
https://github.com/theforeman/foreman_cockpit/commit/4a4a527236d8efd1991c646978376e595f7e8112

**Comment by dLobatog** [comment]
@worsco Yup, I was waiting to release a new version with more fixes but it wouldn't hurt to release a patch version 2.0.2 with this. I'll keep you posted.

**Comment by worsco** [comment]
@dLobatog Thank you & much appreciated.  Looking forward for a patched RPM pushed to General Availability.

**Comment by dLobatog** [comment]
Feel free to track it through:

https://github.com/theforeman/foreman-packaging/pull/1258 
https://github.com/theforeman/foreman-packaging/pull/1257

2.0.2 is out as a rubygem already, just waiting on the releasers for these 2, the person who usually reviews foreman-packaging is out for the week, so it'll take a bit longer than usual, my apologies. If your Foreman installation is small you can locate the file and patch it in the meantime.
